name: rafa_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  image_picker: ^0.8.4+3
  video_player: ^2.2.6
  geocoding: ^2.0.1
  flutter_map: ^1.0.0
  flutter_map_marker_cluster: any
  latlong2: 0.8.1
  positioned_tap_detector_2: ^1.0.4
  dropdown_search: ^2.0.1
  flutter_easyloading: ^3.0.0
  flutter_typeahead: ^3.2.0
  dio: ^4.0.4
  dotted_border: ^2.0.0+2
  footer: ^0.0.4
  json_table: ^2.0.1
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.2
  mime: ^1.0.1
  universal_io: ^2.0.4
  mobile_scanner:
    git:
      url: https://github.com/juliansteenbakker/mobile_scanner
  timer_count_down: ^2.2.1
  universal_html: ^2.0.8
  location: ^4.4.0
  js: ^0.6.4
  g_recaptcha_v3: ^0.0.5
  geolocator: ^9.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  assets:
    - assets/images/
  fonts:
    - family: Barlow
      fonts:
        - asset: fonts/Barlow-Regular.ttf
        - asset: fonts/Barlow-Medium.ttf
          weight: 500
        - asset: fonts/Barlow-SemiBold.ttf
          weight: 600
        - asset: fonts/Barlow-Bold.ttf
          weight: 700
        - asset: fonts/Barlow-BoldItalic.ttf
          weight: 700
          style: italic
        # - asset: fonts/Barlow-Black.ttf
        # - asset: fonts/Barlow-BlackItalic.ttf
        # - asset: fonts/Barlow-ExtraBold.ttf
        # - asset: fonts/Barlow-ExtraBoldItalic.ttf
        # - asset: fonts/Barlow-ExtraLight.ttf
        # - asset: fonts/Barlow-ExtraLightItalic.ttf
        # - asset: fonts/Barlow-Italic.ttf
        # - asset: fonts/Barlow-Light.ttf
        # - asset: fonts/Barlow-LightItalic.ttf
        
        # - asset: fonts/Barlow-MediumItalic.ttf
        
        # - asset: fonts/Barlow-SemiBold.ttf
        # - asset: fonts/Barlow-SemiBoldItalic.ttf
        # - asset: fonts/Barlow-Thin.ttf
        # - asset: fonts/Barlow-ThinItalic.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: sgds-icons
      fonts:
        - asset: fonts/sgds-icons.ttf
  uses-material-design: true
